---
title: "DumbDeseq: RNA Expression Analysis Project"
output: html_notebook
---
```{r}
library(ggplot2)
library(dplyr)
library(RColorBrewer)
library(ggrepel)
Genes <- RNA.exper
head(Genes)
```
```{r}
Genes <- Genes %>%
  mutate(diffexpressed = case_when(
    log2FoldChange > 1 & pvalue < 0.01 ~ "Upregulated",
    log2FoldChange < -1 & pvalue < 0.01 ~ "Downregulated",
    TRUE ~ "Not significant"))

```
```{r}
ggplot(data = Genes, aes(x = log2FoldChange, y = -log10(pvalue), col = diffexpressed)) +
  geom_point(size = 1.5, alpha = 0.6) +  
  geom_vline(xintercept = c(-1, 1), linetype = "dashed", col = "red") +
  geom_hline(yintercept = -log10(0.01), linetype = "dashed", col = "blue") +
  scale_color_manual(
    values = c("Downregulated" = "blue", 
               "Not significant" = "grey", 
               "Upregulated" = "red")
  ) +
  labs(
    title = "Differential Gene Expression",
    x = "Log2 Fold",
    y = "p-value",
    color = "Expression"
  ) +
  theme(
    axis.title.y = element_text(face = "bold", margin = margin(0,20,0,0), size = rel(1.1), color = 'black'),
    axis.title.x = element_text(hjust = 0.5, face = "bold", margin = margin(20,0,0,0), size = rel(1.1), color = 'black'),
    plot.title = element_text(hjust = 0.5),
 legend.position = "topright") +
  theme_set(theme_classic(base_size = 20))
```
```{r}
up_genes <- Genes %>%
  filter(log2FoldChange > 1 & pvalue < 0.01)

down_genes <- Genes %>%
  filter(log2FoldChange < -1 & pvalue < 0.01)
cat("Number of upregulated genes:", nrow(up_genes), "\n")
cat("Number of downregulated genes:", nrow(down_genes), "\n")
```
```{r}
head(down_genes, 5)
```
```{r}
head(up_genes, 5)
